// <auto-generated />
using System;
using Injera.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Injera.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20240915122023_UpdateMenuItemsImageUrl2")]
    partial class UpdateMenuItemsImageUrl2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Habesha"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Italian"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Beef with black cardamom & spiced butter Mitmita served with injera.",
                            ImageUrl = "/images/kitfo.jpg",
                            Name = "Kitfo",
                            Price = 325.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lean & tender cubes of beef spiced with butter 'Mitmita Spice' served with injera.",
                            ImageUrl = "/images/gored.jpg",
                            Name = "Gored Gored",
                            Price = 325.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Grilled biff prepared with onion, garlic, oil and green papper served with injera.",
                            ImageUrl = "/images/firfir.webp",
                            Name = "Tibsi Firfir",
                            Price = 349.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Lean & tender cubes of beef spiced with butter 'Mitmita Spice' served with injera.",
                            ImageUrl = "/images/xaida.jpg",
                            Name = "White Tibsi",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Strips of beef steked with butter, traditional herbs, spices ans served with injera.",
                            ImageUrl = "/images/zilzil.webp",
                            Name = "Zilzil Tibsi",
                            Price = 349.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Beef meat prepared with onion berbere pepper and butter served with injera.",
                            ImageUrl = "/images/qeyhTibsi.jpg",
                            Name = "Keyh Wet",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Beef meat prepared with onion berbere pepper and butter served with injera.",
                            ImageUrl = "/images/qeyh.jpg",
                            Name = "Red Tibsi",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "a combination of exotic national dishes Mosob style served with injera. .",
                            ImageUrl = "/images/beyaynetu.jpeg",
                            Name = "Huset's Special",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Classic pizza with tomato, mozzarella, and basil.",
                            ImageUrl = "/images/margarita.jpg",
                            Name = "Margherita Pizza",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Pasta with eggs, cheese, pancetta, and pepper.",
                            ImageUrl = "/images/carbonara.jpg",
                            Name = "Pasta Carbonara",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Baked layers of pasta with beef ragu and bechamel sauce.",
                            ImageUrl = "/images/lasagna.jpg",
                            Name = "Lasagna",
                            Price = 160.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Spaghetti with slow-cooked meat sauce.",
                            ImageUrl = "/images/bolognese.jpeg",
                            Name = "Spaghetti Bolognese",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Creamy rice dish with mushrooms and Parmesan.",
                            ImageUrl = "/images/risotto.webp",
                            Name = "Risotto",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Pasta tossed with butter, Parmesan, and cream.",
                            ImageUrl = "/images/alfredo.jpg",
                            Name = "Fettuccine Alfredo",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Grilled bread topped with tomatoes, basil, and olive oil.",
                            ImageUrl = "/images/Bruschetta.jpg",
                            Name = "Bruschetta",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Traditional Italian coffee-flavored dessert.",
                            ImageUrl = "/images/Tiramisu.webp",
                            Name = "Tiramisu",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Soft dough dumplings served with a tomato sauce.",
                            ImageUrl = "/images/Gnocchi.jpg",
                            Name = "Gnocchi",
                            Price = 135.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Italian coffee drink with steamed milk foam.",
                            ImageUrl = "/images/Cappuccino.webp",
                            Name = "Cappuccino",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Rich and bold Italian coffee.",
                            ImageUrl = "/images/Espresso.webp",
                            Name = "Espresso",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Full-bodied red wine.",
                            ImageUrl = "/images/redw.jpeg",
                            Name = "Red Wine",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Freshly squeezed lemonade.",
                            ImageUrl = "/images/Lemonade.jpg",
                            Name = "Lemonade",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Chilled sparkling water.",
                            ImageUrl = "/images/Mineral.png",
                            Name = "Mineral Water",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Chilled iced tea with lemon.",
                            ImageUrl = "/images/Iced.jpg",
                            Name = "Iced Tea",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Fruity alcoholic beverage.",
                            ImageUrl = "/images/Cocktail.jpg",
                            Name = "Cocktail",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Refreshing cold beer.",
                            ImageUrl = "/images/beer.jpg",
                            Name = "Beer",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Warm and comforting chocolate drink.",
                            ImageUrl = "/images/hotchaco.jpg",
                            Name = "Hot Chocolate",
                            Price = 40.00m
                        });
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
